- name: Generate index.html
  run: |
    # List all HTML files except index.html
    html_files=$(find . -type f -name "*.html" | grep -v "index.html" | sort)
    
    # Create header for index.html
    cat > index.html << 'EOF'
    <!DOCTYPE html>
    <html>
    <head>
      <title>HealthMedic Site Map</title>
      <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
        h1 { color: #333; }
        ul { list-style-type: none; padding: 0; }
        li { margin: 10px 0; }
        a { text-decoration: none; color: #0066cc; transition: color 0.2s; }
        a:hover { color: #0044aa; }
        .file-path { color: #666; font-size: 0.9em; }
      </style>
    </head>
    <body>
      <h1>HealthMedic Site Map</h1>
      <ul>
    EOF
    
    # Add links for each HTML file
    for file in $html_files; do
      # Format file name (remove .html and convert to title case)
      file_name=$(basename "$file" .html)
      title=$(echo "$file_name" | sed 's/_/ /g' | awk '{for(i=1;i<=NF;i++){sub(/^./,toupper(substr($i,1,1)),$i)}}1')
      
      # Convert file path to GitHub Pages absolute URL
      gh_url=$(echo "$file" | sed 's|^\./||')
      absolute_url="/healthmedic/$gh_url"
      
      # Add link to index.html with absolute path
      echo "            <li><a href=\"$absolute_url\">$title</a><br><span class=\"file-path\">$absolute_url</span></li>" >> index.html
    done
    
    # Close index.html
    cat >> index.html << 'EOF'
      </ul>
      <p>Last updated: $(date)</p>
    </body>
    </html>
    EOF
    
    # Print the generated index.html for debugging
    echo "Generated index.html content:"
    cat index.html
