name: Update Index Page
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate index.html
      run: |
        # List all HTML files except index.html
        html_files=$(find . -type f -name "*.html" | grep -v "index.html" | sort)
        
        # Create header for index.html
        cat > index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <title>HealthMedic Site Map</title>
          <style>
            body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
            h1 { color: #333; }
            ul { list-style-type: none; padding: 0; }
            li { margin: 10px 0; }
            a { text-decoration: none; color: #0066cc; transition: color 0.2s; }
            a:hover { color: #0044aa; }
            .file-path { color: #666; font-size: 0.9em; }
          </style>
        </head>
        <body>
          <h1>HealthMedic Site Map</h1>
          <ul>
        EOF
        
        # Add links for each HTML file
        for file in $html_files; do
          # Format file name (remove .html and convert to title case)
          file_name=$(basename "$file" .html)
          title=$(echo "$file_name" | sed 's/_/ /g' | awk '{for(i=1;i<=NF;i++){sub(/^./,toupper(substr($i,1,1)),$i)}}1')
          
          # Add link to index.html
          echo "            <li><a href=\"$file\">$title</a><br><span class=\"file-path\">$file</span></li>" >> index.html
        done
        
        # Close index.html
        cat >> index.html << 'EOF'
          </ul>
        </body>
        </html>
        EOF
        
        # Print the generated index.html for debugging
        echo "Generated index.html content:"
        cat index.html

    - name: Commit changes
      run: |
        # Check if index.html was modified
        if git diff --quiet index.html; then
          echo "No changes to index.html, skipping commit."
        else
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Update index.html sitemap" || true
          git push
        fi
